<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-7SBKKJ1" failures="4" tests="12" name="SMR_Call_Dispostion_Data_Check_And_CCM_Reports.CCM_Cross_sell_Intrest_Log_Reports" time="128.064" errors="0" timestamp="2024-12-03T18:12:18 IST" skipped="0">
  <testcase classname="SMR_Call_Dispostion_Data_Check_And_CCM_Reports.CCM_Cross_sell_Intrest_Log_Reports" name="Username" time="1.372"/>
  <system-out/>
  <testcase classname="SMR_Call_Dispostion_Data_Check_And_CCM_Reports.CCM_Cross_sell_Intrest_Log_Reports" name="Password" time="1.585"/>
  <system-out/>
  <testcase classname="SMR_Call_Dispostion_Data_Check_And_CCM_Reports.CCM_Cross_sell_Intrest_Log_Reports" name="Captcha" time="2.237"/>
  <system-out/>
  <testcase classname="SMR_Call_Dispostion_Data_Check_And_CCM_Reports.CCM_Cross_sell_Intrest_Log_Reports" name="SUBMIT_Button" time="2.169"/>
  <system-out/>
  <testcase classname="SMR_Call_Dispostion_Data_Check_And_CCM_Reports.CCM_Cross_sell_Intrest_Log_Reports" name="Click_On_SMR" time="18.755"/>
  <system-out/>
  <testcase classname="SMR_Call_Dispostion_Data_Check_And_CCM_Reports.CCM_Cross_sell_Intrest_Log_Reports" name="Click_Reports" time="1.099"/>
  <system-out/>
  <testcase classname="SMR_Call_Dispostion_Data_Check_And_CCM_Reports.CCM_Cross_sell_Intrest_Log_Reports" name="Click_On_The_Cross_sell_Intrest" time="3.129"/>
  <system-out/>
  <testcase classname="SMR_Call_Dispostion_Data_Check_And_CCM_Reports.CCM_Cross_sell_Intrest_Log_Reports" name="Dealer_Parent_Group_Wise" time="27.262">
    <failure message="No Data Found for Dealer_Parent_Group_wise In Cross_Sell_Intrest_Log : 0" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Data Found for Dealer_Parent_Group_wise In Cross_Sell_Intrest_Log : 0
at org.testng.Assert.fail(Assert.java:99)
at SMR_Call_Dispostion_Data_Check_And_CCM_Reports.CCM_Cross_sell_Intrest_Log_Reports.Dealer_Parent_Group_Wise(CCM_Cross_sell_Intrest_Log_Reports.java:159)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Dealer_Parent_Group_Wise -->
  <system-out/>
  <testcase classname="SMR_Call_Dispostion_Data_Check_And_CCM_Reports.CCM_Cross_sell_Intrest_Log_Reports" name="WorkShop_Wise" time="23.524">
    <failure message="No Data Found for Workshop_Wise In Cross_Sell_Intrest_Log : 0" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Data Found for Workshop_Wise In Cross_Sell_Intrest_Log : 0
at org.testng.Assert.fail(Assert.java:99)
at SMR_Call_Dispostion_Data_Check_And_CCM_Reports.CCM_Cross_sell_Intrest_Log_Reports.WorkShop_Wise(CCM_Cross_sell_Intrest_Log_Reports.java:249)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- WorkShop_Wise -->
  <system-out/>
  <testcase classname="SMR_Call_Dispostion_Data_Check_And_CCM_Reports.CCM_Cross_sell_Intrest_Log_Reports" name="Day_Wise" time="23.467">
    <failure message="No Data Found for Day_Wise In Cross_Sell_Intrest_Log : 0" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Data Found for Day_Wise In Cross_Sell_Intrest_Log : 0
at org.testng.Assert.fail(Assert.java:99)
at SMR_Call_Dispostion_Data_Check_And_CCM_Reports.CCM_Cross_sell_Intrest_Log_Reports.Day_Wise(CCM_Cross_sell_Intrest_Log_Reports.java:338)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Day_Wise -->
  <system-out/>
  <testcase classname="SMR_Call_Dispostion_Data_Check_And_CCM_Reports.CCM_Cross_sell_Intrest_Log_Reports" name="Service_type_Wise" time="23.465">
    <failure message="No Data Found for Service_type_Wise In Cross_Sell_Intrest_Log : 0" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Data Found for Service_type_Wise In Cross_Sell_Intrest_Log : 0
at org.testng.Assert.fail(Assert.java:99)
at SMR_Call_Dispostion_Data_Check_And_CCM_Reports.CCM_Cross_sell_Intrest_Log_Reports.Service_type_Wise(CCM_Cross_sell_Intrest_Log_Reports.java:428)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Service_type_Wise -->
  <system-out/>
  <testcase classname="SMR_Call_Dispostion_Data_Check_And_CCM_Reports.CCM_Cross_sell_Intrest_Log_Reports" name="Comparison_0f_all_Data" time="0.000"/>
  <system-out/>
</testsuite> <!-- SMR_Call_Dispostion_Data_Check_And_CCM_Reports.CCM_Cross_sell_Intrest_Log_Reports -->
