<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-7SBKKJ1" failures="1" tests="8" name="USER_Admin_Reports.Dialer_Call_Analysis" time="60.859" errors="0" timestamp="2024-12-11T18:24:34 IST" skipped="0">
  <testcase classname="USER_Admin_Reports.Dialer_Call_Analysis" name="Username" time="0.797"/>
  <system-out/>
  <testcase classname="USER_Admin_Reports.Dialer_Call_Analysis" name="Password" time="0.862"/>
  <system-out/>
  <testcase classname="USER_Admin_Reports.Dialer_Call_Analysis" name="Captcha" time="0.756"/>
  <system-out/>
  <testcase classname="USER_Admin_Reports.Dialer_Call_Analysis" name="SUBMIT_Button" time="0.201"/>
  <system-out/>
  <testcase classname="USER_Admin_Reports.Dialer_Call_Analysis" name="Remove_PouP" time="0.703"/>
  <system-out/>
  <testcase classname="USER_Admin_Reports.Dialer_Call_Analysis" name="Click_On_Reports" time="5.717"/>
  <system-out/>
  <testcase classname="USER_Admin_Reports.Dialer_Call_Analysis" name="Click_On_Dialer_Call_Analysis" time="0.131"/>
  <system-out/>
  <testcase classname="USER_Admin_Reports.Dialer_Call_Analysis" name="Verify_Dialer_Call_Analysis_Data" time="51.692">
    <failure message="  Dialer Call Analysis  does not contain any data." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError:   Dialer Call Analysis  does not contain any data.
at org.testng.Assert.fail(Assert.java:99)
at USER_Admin_Reports.Dialer_Call_Analysis.verifyReportData(Dialer_Call_Analysis.java:123)
at USER_Admin_Reports.Dialer_Call_Analysis.Verify_Dialer_Call_Analysis_Data(Dialer_Call_Analysis.java:65)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Verify_Dialer_Call_Analysis_Data -->
  <system-out/>
</testsuite> <!-- USER_Admin_Reports.Dialer_Call_Analysis -->
